/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Final_Merged.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[135.72, 94.39, -12.68]}>
        <skinnedMesh
          geometry={nodes["haiir-male_Nurbs_-_Guia_de_caminho007_1"].geometry}
          material={materials["Mat.2"]}
          skeleton={nodes["haiir-male_Nurbs_-_Guia_de_caminho007_1"].skeleton}
        />
      </group>
      <skinnedMesh
        geometry={nodes.Boy_1.geometry}
        material={materials.Mat}
        skeleton={nodes.Boy_1.skeleton}
      />
      <primitive object={nodes.mixamorigHips} />
    </group>
  );
}

useGLTF.preload("/Final_Merged.gltf");
